name: Build Python Docker Image

on:
  workflow_call:  # Allows other repos to call this workflow
    inputs:
      docker_image:
        required: true
        type: string  # Docker image name
      docker_tag:
        required: false
        default: latest
        type: string  # Docker image tag (default is "latest")
    secrets:
      docker_username:  # Requires Docker username
      docker_password:  # Requires Docker password

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Build Docker Image
        run: docker build -t ${{ inputs.docker_image }}:${{ inputs.docker_tag }} .

      - name: Push Docker Image
        run: docker push ${{ inputs.docker_image }}:${{ inputs.docker_tag }}
